# Generated by Django 5.1 on 2024-08-21 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Não iniciada', 'Nao Iniciada'), ('Em andamento', 'Em Andamento'), ('Concluído', 'Concluido')], max_length=20)),
                ('priority', models.CharField(choices=[('Atenção', 'Atencao'), ('Baixa', 'Baixa'), ('Alta', 'Alta')], max_length=20)),
            ],
            options={
                'verbose_name': 'Notion',
                'verbose_name_plural': 'Notions',
            },
        ),
    ]
