# Generated by Django 5.1 on 2024-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='notion_page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
